U1/BlibliotecaApp/Controllers/AutorController.cs
using BlibliotecaApp.Models;
using BlibliotecaApp.Services;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BlibliotecaApp.Controllers
{
    public class AutorController : Controller
    {
        private readonly IAutorService _autorService = new AutorService();

        // GET: Autor
        public async Task<ActionResult> MainAutor()
        {
            bool auxP = TempData["AuxP"] != null ? (bool)TempData["AuxP"] : true;

            List<AutorModel> autorList = await _autorService.ListaAutores();
            return View(autorList);
        }

        public async Task<ActionResult> FormularioAutor(string id)
        {
            var ASUX = id;
            AutorModel autorModel = new AutorModel();
            bool auxP = TempData["AuxP"] != null ? (bool)TempData["AuxP"] : true;


            if (id != null)
            {
                ViewBag.Acction = "Editar Autor";
                auxP = !auxP;
                TempData["AuxP"] = auxP;
                autorModel = await _autorService.BuscarAutor(id);
            }
            else
            {
                ViewBag.Acction = "Nuevo Autor";
                auxP = auxP;
                TempData["AuxP"] = auxP;
            }

            return View(autorModel);
        }


        [HttpPost]
        public async Task<ActionResult> GuardarAutor(string id_autor, string nombre_autor, string nacionalidad_autor, AutorModel autorModel)
        {
            bool response = false;
            bool auxP = TempData["AuxP"] != null ? (bool)TempData["AuxP"] : true;

            if (auxP)
            {
                // Crear un nuevo autor
                response = await _autorService.GuardarAutor(autorModel);
            }
            else
            {
                // Editar autor existente
                response = await _autorService.EditarAutor(autorModel);
            }

            if (response)
            {
                return RedirectToAction("FormularioAutor");
            }
            else
            {
                return RedirectToAction("FormularioAutor");
            }
        }


        [HttpPost]
        public async Task<ActionResult> EliminarAutor(string id)
        {
            var response = await _autorService.EliminarAutor(id);
            if (response)
            {
                return RedirectToAction("MainAutor");
            }
            else
            {
                return RedirectToAction("MainAutor");
            }
        }
    }
}

U1/BlibliotecaApp/Controllers/ClienteController.cs
using BlibliotecaApp.Models;
using BlibliotecaApp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BlibliotecaApp.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteService _clienteService = new ClienteService();

        // GET: Cliente
        public async Task<ActionResult> MainCliente()
        {
            bool AuxC = TempData["AuxC"] != null ? (bool)TempData["AuxC"] : true;

            List<ClienteModel> clientesList = await _clienteService.ListaClientes();
            return View(clientesList);
        }

        public async Task<ActionResult> FormularioCliente(string id)
        {
            var ASUX = id;
            ClienteModel clienteModel = new ClienteModel();
            bool AuxC = TempData["AuxC"] != null ? (bool)TempData["AuxC"] : true;


            if (id != null)
            {
                ViewBag.Acction = "Editar Cliente";
                AuxC = !AuxC;
                TempData["AuxC"] = AuxC;
                clienteModel = await _clienteService.BuscarCliente(id);
            }
            else
            {
                ViewBag.Acction = "Nuevo Cliente";
                AuxC = AuxC;
                TempData["AuxC"] = AuxC;
            }

            return View(clienteModel);
        }

        [HttpPost]
        public async Task<ActionResult> GuardarCliente(ClienteModel clienteModel)
        {
            bool response = false;
            bool AuxC = TempData["AuxC"] != null ? (bool)TempData["AuxC"] : true;
            var auxAAAA = AuxC;

            if (AuxC)
            {
                response = await _clienteService.GuardarCliente(clienteModel);
            }
            else
            {
                response = await _clienteService.EditarCliente(clienteModel);
            }

            if (response)
            {
                return RedirectToAction("FormularioCliente");
            }
            else
            {
                return RedirectToAction("FormularioCliente");
            }
        }


        [HttpPost]
        public async Task<ActionResult> EliminarCliente(string id)
        {
            var response = await _clienteService.EliminarCliente(id);
            if (response)
            {
                return RedirectToAction("MainCliente");
            }
            else
            {
                return RedirectToAction("MainCliente");
            }
        }



    }
}

U1/BlibliotecaApp/Controllers/GeneroController.cs
using BlibliotecaApp.Models;
using BlibliotecaApp.Services;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BlibliotecaApp.Controllers
{
    public class GeneroController : Controller
    {
        private readonly IGeneroService _generoService = new GeneroService();

        // GET: Genero
        public async Task<ActionResult> MainGenero()
        {
            bool auxP = TempData["AuxP"] != null ? (bool)TempData["AuxP"] : true;

            List<GeneroModel> generoList = await _generoService.ListaGeneros();
            return View(generoList);
        }

        public async Task<ActionResult> FormularioGenero(string id)
        {
            var ASUX = id;
            GeneroModel generoModel = new GeneroModel();
            bool auxP = TempData["AuxP"] != null ? (bool)TempData["AuxP"] : true;


            if (id != null)
            {
                ViewBag.Acction = "Editar Genero";
                auxP = !auxP;
                TempData["AuxP"] = auxP;
                generoModel = await _generoService.BuscarGenero(id);
            }
            else
            {
                ViewBag.Acction = "Nuevo Genero";
                auxP = auxP;
                TempData["AuxP"] = auxP;
            }

            return View(generoModel);
        }


        [HttpPost]
        public async Task<ActionResult> GuardarGenero(string id_genero, string nombre_genero, string descripcion_genero, GeneroModel generoModel)
        {
            bool response = false;
            bool auxP = TempData["AuxP"] != null ? (bool)TempData["AuxP"] : true;

            if (auxP)
            {
                // Crear un nuevo autor
                response = await _generoService.GuardarGenero(generoModel);
            }
            else
            {
                // Editar autor existente
                response = await _generoService.EditarGenero(generoModel);
            }

            if (response)
            {
                return RedirectToAction("FormularioGenero");
            }
            else
            {
                return RedirectToAction("FormularioGenero");
            }
        }


        [HttpPost]
        public async Task<ActionResult> EliminarGenero(string id)
        {
            var response = await _generoService.EliminarGenero(id);
            if (response)
            {
                return RedirectToAction("MainGenero");
            }
            else
            {
                return RedirectToAction("MainGenero");
            }
        }
    }
}

U1/BlibliotecaApp/Controllers/LibroController.cs
using BlibliotecaApp.Models;
using BlibliotecaApp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BlibliotecaApp.Controllers
{
    public class LibroController : Controller
    {
        private readonly ILibroService _libroService = new LibroService();
        // GET: Libro
        public async Task<ActionResult> MainLibro()
        {
            bool auxP = TempData["AuxP"] != null ? (bool)TempData["AuxP"] : true;

            List<LibroModel> libroList = await _libroService.ListaLibros();
            return View(libroList);
        }

        public async Task<ActionResult> FormularioLibro(string id)
        {
            var ASUX = id;
            LibroModel libroModel = new LibroModel();
            bool auxP = TempData["AuxP"] != null ? (bool)TempData["AuxP"] : true;


            if (id != null)
            {
                ViewBag.Acction = "Editar Libro";
                auxP = !auxP;
                TempData["AuxP"] = auxP;
                libroModel = await _libroService.BuscarLibro(id);
            }
            else
            {
                ViewBag.Acction = "Nuevo Libro";
                auxP = auxP;
                TempData["AuxP"] = auxP;
            }

            return View(libroModel);
        }


        [HttpPost]
        public async Task<ActionResult> GuardarLibro(LibroModel libroModel)
        {
            bool response = false;
            bool auxP = TempData["AuxP"] != null ? (bool)TempData["AuxP"] : true;

            if (auxP)
            {
                // Crear un nuevo autor
                response = await _libroService.GuardarLibro(libroModel);
            }
            else
            {
                // Editar autor existente
                response = await _libroService.EditarLibro(libroModel);
            }

            if (response)
            {
                return RedirectToAction("FormularioLibro");
            }
            else
            {
                return RedirectToAction("FormularioLibro");
            }
        }


        [HttpPost]
        public async Task<ActionResult> EliminarLibro(string id)
        {
            var response = await _libroService.EliminarLibro(id);
            if (response)
            {
                return RedirectToAction("MainLibro");
            }
            else
            {
                return RedirectToAction("MainLibro");
            }
        }
    }
}

U1/BlibliotecaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Biblioteca</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- Masthead-->
    <header class="masthead">
        <div class="container px-4 px-lg-5 h-100">
            <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-8 align-self-end">
                    <h1 class="text-white font-weight-bold">Tu lugar favorito para encontrar los mejores libros</h1>
                    <hr class="divider" />
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <p class="text-white-75 mb-5">Puedes encontrar tus libros favoritos ya que poseemos una amplia gama de generos literarios para todo publico.</p>
                    <a class="btn btn-primary btn-xl" href="#portfolio">Administración</a>
                </div>
            </div>
        </div>
    </header>

    <!-- Services-->
    <section class="page-section" id="services">
        <div class="container px-4 px-lg-5">
            <h2 class="text-center mt-0">Módulo de Administración</h2>
            <hr class="divider" />
        </div>
    </section>
    <!-- Portfolio-->
    <div id="portfolio" class="container align-content-center">
        <div class="container-fluid p-5">
            <div class="row g-5">
                <div class="col-lg-6 col-sm-6">
                    <a class="portfolio-box" href="@Url.Action("MainPrestamo", "Prestamo")" title="Prestamos">
                        <img class="img-fluid" src="~/assets/img/prestamoBiblioteca.jpg" alt="..." />
                        <div class="portfolio-box-caption">
                            <div class="project-name">Prestamos</div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <a class="portfolio-box" href="@Url.Action("MainCliente", "Cliente")" title="Clientes">
                        <img class="img-fluid" src="~/assets/img/clientesBiblioteca.jpeg" alt="..." />
                        <div class="portfolio-box-caption">
                            <div class="project-name">Clientes</div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <a class="portfolio-box" href="@Url.Action("MainAutor", "Autor")" title="Project Name">
                        <img class="img-fluid" src="~/assets/img/portfolio/Autores.jpg" alt="..." />
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">Administración</div>
                            <div class="project-name">Autores</div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <a class="portfolio-box" href="@Url.Action("MainEditorial", "Editorial")" title="Project Name">
                        <img class="img-fluid" src="~/assets/img/portfolio/fullsize/1.jpg" alt="..." />
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">Administración</div>
                            <div class="project-name">Editoriales</div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <a class="portfolio-box" href="@Url.Action("MainGenero", "Genero")" title="Project Name">
                        <img class="img-fluid" src="~/assets/img/portfolio/generosApi.jpg" alt="..." />
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">Administración</div>
                            <div class="project-name">Género</div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <a class="portfolio-box" href="@Url.Action("MainLibro", "Libro")" title="Project Name">
                        <img class="img-fluid" src="~/assets/img/portfolio/librosApi.jpg" alt="..." />
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">Administración</div>
                            <div class="project-name">Libros</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <!-- Footer-->
    <footer class="bg-light py-5">
        <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2024 - Tu Biblioteca</div></div>
    </footer>



    <!-- Navigation

         @Html.ActionLink("Prestamos", "MainPrestamo")

                @RenderBody()

                <li></li>
        <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
             <hr />
     <footer>
         <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
     </footer>

    -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>